---
- name: Create autologin conf dir
  file:
    path: /etc/systemd/system/getty@tty1.service.d
    state: directory
  become: True

- name: Run whoami without become.
  command: whoami
  changed_when: false
  become: false
  register: startup_username 

- name: Configure autologin 
  template: 
    src: templates/autologin.conf.j2
    dest: /etc/systemd/system/getty@tty1.service.d/override.conf
  become: True

- name: Added autostartx to zprofile
  copy:
    src: zprofile 
    dest: ~/.zprofile 
