--- 
- name: Install docker packages
  package:
    name: docker
    state: present
  become: yes

- name: Install docker-compose packages
  package:
    name: docker-compose
    state: present
  become: yes

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: 'started'
    enabled: 'yes'
  become: yes

- name: Ensure docker users are added to the docker group.
  user:
    name: '{{ dt_user }}'
    groups: docker
    append: yes
  become: yes
