---
- name: Install Rider
  shell: |
    mkdir -p {{install_path}}
    curl -L "{{ download_url }}" | tar xvz -C {{ install_path }} --strip 1
  args:
    creates: "{{install_path}}"
  vars:
    download_url: "https://download.jetbrains.com/product?code=RD&latest&distribution=linux"
    install_path: "{{ programs_dir }}/rider"
  tags:
    - rider
    - ide

- name: Create Rider Desktop Entry
  template:
    src: templates/rider.desktop.j2
    dest: /usr/share/applications/rider.desktop
  become: true

- name: Install CSharp packages
  package:
    name:
      - dotnet-host
      - dotnet-runtime
      - dotnet-sdk
      - mono
      - nuget
    state: present
  become: True

  #- name: Install CSharp (AUR) packages
  #  aur:
  #    name:
  #      - msbuild-16-bin
  #    skip_installed: yes


