---
- hosts: all
  roles:
    - { role: packages-base, tags: packages-base }
    - { role: zsh, tags: zsh } 
    - { role: neovim, tags: neovim } 
    - { role: screen, tags: screen } 
    - { role: xprofile, tags: xprofile } 
    - { role: packages-desktop, tags: packages-desktop } 
    - { role: audio, tags: audio } 
    - { role: fonts, tags: fonts } 
    - { role: gtk, tags: gtk } 
    - { role: i3-wm, tags: i3-wm } 
    - { role: i3-lock, tags: i3-lock } 
    - { role: picom, tags: picom } 
    - { role: polybar, tags: polybar } 
    - { role: kitty, tags: kitty } 
    - { role: rofi, tags: rofi } 
    - { role: neofetch, tags: neofetch } 

