---
- hosts: all
  roles:
    - { role: packages-base, tags: packages-base }
    - { role: zsh, tags: zsh } 
    - { role: neovim, tags: neovim } 
    - { role: screen, tags: screen } 
    - { role: xprofile, tags: xprofile } 
    - { role: packages-desktop, tags: packages-desktop } 
    - { role: gtk, tags: gtk } 
    - { role: i3-wm, tags: i3-wm } 
    - { role: picom, tags: picom } 
    - { role: polybar, tags: polybar } 

