---
- name: Install PhpStorm
  shell: |
    mkdir -p "{{install_path}}"
    curl -L "{{ download_url }}" | tar xvz -C "{{ install_path }}" --strip 1
  args:
    creates: "{{install_path}}"
  vars:
    download_url: "https://download.jetbrains.com/product?code=PS&latest&distribution=linux"
    install_path: "{{ lookup('env','PROGRAMS_PATH')|d('~/programs',true) }}/phpstorm"
  tags:
    - phpstorm
    - ide


