# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false 
  
    # Customize the amount of memory on the VM:
    vb.name = "archlinux_dotfiles"
    vb.memory = "1024"
    vb.cpus = 2

    vb.customize [
       "modifyvm", :id,
       "--audio", "alsa",
       "--audiocontroller", "AC97"
    ]
  end

  config.vm.provision "shell", inline: <<-SHELL
    # SWAP
    fallocate -l 1G /swapfile
    mkswap /swapfile
    swapon /swapfile
    echo "/swapfile none swap defaults 0 0" >> /etc/fstab
    
    # TMP
    mount -o remount,size=1G /tmp
    
    # UPGRADE
    pacman -Syu --noconfirm
    pacman -S --noconfirm fakeroot file python make gcc pkg-config which perl automake autoconf gettext patch

    # DEPS
    pacman -S --noconfirm ansible git

    # DOTFILES
    mkdir -p /home/vagrant/dotfiles
  SHELL

  config.vm.synced_folder ".", "/home/vagrant/dotfiles/", type: "rsync", rsync__exclude: [".git/", ".vagrant.d/"]

  $script = <<-SCRIPT
    # EXEC
    cd $HOME/dotfiles
    ansible-playbook -i docker/hosts install.yml
    echo -e "vagrant" | chsh -s '/usr/bin/zsh'
  SCRIPT

  config.vm.provision "shell", inline: $script, privileged: false
end
