# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false 
  
    # Customize the amount of memory on the VM:
    vb.name = "archlinux_dotfiles"
    vb.memory = "1024"
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    # SWAP
    fallocate -l 1G /swapfile
    mkswap /swapfile
    swapon /swapfile
    echo "/swapfile none swap defaults 0 0" >> /etc/fstab
    
    # TMP
    mount -o remount,size=1G /tmp
    
    # UPGRADE
    pacman -Syu --noconfirm

    # DEPS
    pacman -S --noconfirm ansible git

    # DOTFILES
    mkdir -p /home/vagrant/dotfiles
  SHELL

  config.vm.synced_folder "../", "/home/vagrant/dotfiles/", type: "rsync", rsync__exclude: [".git/", ".vagrant.d/"]

  $script = <<-SCRIPT
    # EXEC
    cd $HOME/dotfiles
    echo "[desktop]\nlocalhost ansible_connection=local" > hosts
    echo -e "vagrant\n/usr/bin/zsh" | chsh
  SCRIPT

  config.vm.provision "shell", inline: $script, privileged: false
end
