---
- name: Install Desktop packages
  package:
    name:
      - xorg-server
      - xorg-xinit
      - xclip
      - xorg-xrdb
      - xorg-xfd
      - xorg-xrandr 
      - networkmanager-openvpn 
      - nm-connection-editor
      - openvpn
      - alsa-utils
      - feh
      # Gui bloat
      - nautilus
      - jgmenu
      - lxappearance
      - arandr
    state: present
  become: True

- name: Install Desktop (AUR) packages
  aur:
    name:
      - yay
    skip_installed: yes

- name: Test host packages file
  stat:
    path: "{{ role_path }}/tasks/by_host/{{ ansible_hostname }}/main.yml"
  register: host_file

- name: Include distribution packages
  include_tasks: "{{ role_path }}/tasks/by_host/{{ ansible_hostname }}/main.yml"
  when: host_file.stat.exists

