---
- name: Install Kitty packages
  package:
    name:
      - kitty
      - kitty-terminfo
    state: present
  become: true

- name: Create config dir 
  file:
    path: ~/.config/kitty
    state: directory

- name: Configure kitty
  copy:
    src: kitty.conf
    dest: ~/.config/kitty/kitty.conf
    backup: yes
