---
- name: Install polybar
  aur:
    name:
      - polybar
      - pacman-contrib
    skip_installed: yes

- name: Create polybar conf dir
  file:
    path: ~/.config/polybar
    state: directory

- name: Copy files
  synchronize:
    src: files/
    dest: ~/.config/polybar/
  notify: restart polybar

- name: Test if node specific template exists for launch.sh
  stat:
    path: "{{ role_path }}/templates/by_host/{{ ansible_hostname }}/launch.j2"
  register: launch_file

- name: Template launch file
  template:
    src: launch.j2
    dest: ~/.config/polybar/launch.sh
    mode: 0755
    backup: yes
  notify: restart polybar

