---
- name: Install i3-wm
  aur:
    name:
      - i3-gaps
      - i3lock-color
    skip_installed: yes

- name: Configure xinitrc
  copy:
    src: xinitrc
    dest: ~/.xinitrc
    backup: yes

- name: Create i3 folder 
  file:
    path: ~/.i3
    state: directory

- name: Template config file
  template:
    src: config.j2
    dest: ~/.i3/config
    backup: yes

- name: Init wallpaper in .xprofile
  copy:
    src: wallpaper.sh
    dest: ~/.xprofile.d/

- name: Configure colors
  copy:
    src: colors
    dest: ~/.Xresources.d/

- name: Init rofi in Xresources
  lineinfile:
    path: ~/.Xresources
    create: yes
    state: present
    line: '#include ".Xresources.d/colors"'
