---
- name: Install i3-wm
  aur:
    name:
      - i3-gaps
      - i3lock-color
    skip_installed: yes

- name: Configure xinitrc
  copy:
    src: xinitrc
    dest: ~/.xinitrc
    backup: yes

- name: Template config file
  template:
    src: config.j2
    dest: ~/.i3/config
    backup: yes

- name: Init wallpaper in .xprofile
  copy:
    src: wallpaper.sh
    dest: ~/.xprofile.d/

- name: Install i3 lock requirements
  package:
    name:
      - scrot
      - imagemagick
      - bc
      - xorg-xdpyinfo
      - xorg-xset
    state: present
  become: yes
  ignore_errors: yes

- name: Clone betterlockscreen
  git:
    repo: https://github.com/pavanjadhaw/betterlockscreen.git
    dest: ~/.config/betterlockscreen
    update: no

- name: Create local bin folder 
  file:
    path: ~/.local/bin/
    state: directory

- name: Copy lockscreen binaries 
  become: true
  copy:
    src: ~/.config/betterlockscreen/betterlockscreen
    dest: /usr/bin/betterlockscreen
    mode: a+x

- name: Generate lockscreen background
  command: betterlockscreen -u ~/dotfiles/wallpapers/wallpaper.jpg

- name: Copy the service 
  become: true
  copy:
    src: ~/.config/betterlockscreen/system/betterlockscreen@.service 
    dest: /etc/systemd/system/betterlockscreen@.service

- name: Register lock service
  command: systemctl enable betterlockscreen@$USER

