---
- name: Install common packages
  package:
    name:
      - curl
      - wget
      - jq
      - fzf
      - rsync
      - which
      - htop
      - networkmanager
      - the_silver_searcher
    state: present
  become: yes
  ignore_errors: yes
 
- name: AUR packages install [Archlinux]
  aur:
    name: kernel-modules-hook
    skip_installed: yes

- name: Test host packages file
  stat:
    path: "{{ role_path }}/tasks/by_host/{{ ansible_hostname }}/main.yml"
  register: host_file

- name: Include host packages
  include_tasks: "{{ role_path }}/tasks/by_host/{{ ansible_hostname }}/main.yml"
  when: host_file.stat.exists
